name: 'Baidu Tieba Auto Sign'

on:
  push:
    branches:
      - main
  schedule:
    - cron: '58 15,20 * * *'

jobs:
  tieba_sign:
    runs-on: ubuntu-latest
    steps:
      - name: '检查代码'
        uses: actions/checkout@v2
      - name: '安装 python'
        uses: actions/setup-python@v1
        with:
          python-version: '3.10.18'
      - name: '安装依赖'
        run: python -m pip install --upgrade requests
      - name: '开始签到'
        env:
          EMAILPASS : ${{secrets.EMAILPASS}}
          BDUSS: ${{ secrets.BDUSS }}
          EMAILSENDER: ${{secrets.EMAILSENDER}}
          EMAILUSER: ${{secrets.EMAILUSER}}
          EMAILHOST: ${{secrets.EMAILHOST}}
          EMAILPORT: ${{secrets.EMAILPORT}}
          EMAITO: ${{secrets.EMAITO}}
        run: python main.py
