name: 'Baidu Tieba Auto Sign'

on:
  push:
    branches:
      - main
  schedule:
    - cron: '15 17,23 * * *'

jobs:
  tieba_sign:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout codes'
        uses: actions/checkout@v2
      - name: 'Set python'
        uses: actions/setup-python@v1
        with:
          python-version: '3.6'
      - name: 'Install dependencies'
        run: python -m pip install --upgrade requests
      - name: 'Start Sign'
        env:
          EMAILPASS : ${{secrets.EMAILPASS}}
          BDUSS: ${{ secrets.BDUSS }}
          EMAILSENDER: ${{secrets.EMAILSENDER}}
          EMAILUSER: ${{secrets.EMAILUSER}}
          EMAILHOST: ${{secrets.EMAILHOST}}
          EMAILPORT: ${{secrets.EMAILPORT}}
          EMAITO: ${{secrets.EMAITO}}
        run: python main.py
